spring:
  config:
    name: database
  datasource:
    url: jdbc:postgresql://localhost:5432/datebase_prak_up
    username: postgres
    password: petrova-05
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: update
    database: postgresql
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    show-sql: true
    properties:
      hibernate:
        format_sql:
server:
  port: 8888

